---
  dataset: "ames_housing"
  bound_dist: [15]
  is_bound_percent: True
  # Ensemble parameters
  alt_type: "multixgb"
  n_disjoint_models: 125
  spread_degree: 17
  mixup_copies: 10
  # Submodel params
  model_params:
    n_estimators: 500
    max_depth: 3
    eval_metric: rmse
    lambda: 1E-2
    gamma: 5E-3
    eta: 1.0
