---
  dataset: "ames_housing"
  bound_dist: [15]
  is_bound_percent: True
  # Ensemble parameters
  alt_type: "multixgb"
  n_disjoint_models: 251
  spread_degree: 17
  mixup_copies: 20
  # Submodel params
  model_params:
    n_estimators: 250
    max_depth: 1
    eval_metric: rmse
    lambda: 1E-1
    gamma: 5E-3
    eta: 1.0
