---
  dataset: "austin_housing"
  bound_dist: [15]
  is_bound_percent: True
  # Ensemble parameters
  alt_type: "multixgb"
  n_disjoint_models: 51
  spread_degree: 13
  mixup_copies: 5
  # Submodel params
  model_params:
    n_estimators: 100
    max_depth: 9
    eval_metric: rmse
    lambda: 1E+2
    gamma: 1E-2
    eta: 1.0
