---
  dataset: "austin_housing"
  bound_dist: [15]
  is_bound_percent: True
  # Ensemble parameters
  alt_type: "multixgb"
  n_disjoint_models: 701
  spread_degree: 13
  mixup_copies: 25
  # Submodel params
  model_params:
    n_estimators: 250
    max_depth: 1
    eval_metric: mae
    lambda: 1E-2
    gamma: 1E-2
    eta: 1.0
