---
  dataset: "diamonds"
  is_classification: False
  bound_dist: [15]
  is_bound_percent: True
  # Ensemble parameters
  alt_type: "knn"
  n_disjoint_models: 1
  spread_degree: 1
  # Submodel params
  model_params:
    n_neighbors: 24273
    metric: minkowski
