---
  dataset: "diamonds"
  is_classification: False
  bound_dist: [15]
  is_bound_percent: True
  # Ensemble parameters
  alt_type: "ridge"
  n_disjoint_models: 1
  spread_degree: 9
  mixup_copies: 0
  # Ridge regression params
  model_params:
    alpha: 3.16E-3
    max_iter: 1E6
    solver: "lsqr"
    tol: 1e-06
