---
  dataset: "life"
  is_classification: False
  bound_dist: [3]
  is_bound_percent: False
  # Ensemble parameters
  alt_type: "xgb"
  n_disjoint_models: 1
  spread_degree: 9
  mixup_copies: 5
  # Submodel params
  model_params:
    n_estimators: 500
    max_depth: 5
    eval_metric: rmse
    lambda: 1E+1
    gamma: 1E-2
    eta: 0.1
